plugins:
  - jekyll-sitemap
  - jekyll-feed

title: YProg
description: Androidアプリを開発しています．『なんか面白いかも，なんか便利かも』をコンセプトに！
author:
  name: YProg
  email: yprogbest@gmail.com
baseurl: ""
url: "https://yprogbest.github.io/"
